/// <reference types="cypress" />

describe('LOI Preview Tests', () => {

    beforeEach(() => {
        cy.login('super-beta@vts.com', 'Creinsights1')
    })

    it('Opening a proposal with no template selected', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2567961")
        cy.get('[data-test=deal-profile-tabs] > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.contains('Please select a template to see an LOI preview')
        cy.get('.u-width-full > .u-relative > .react-dropdown > .loi_template_id__control > .loi_template_id__value-container') 
        cy.get('[data-test=profile-back]').click()   })
    it('Opening a proposal and selecting a template', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2567961")
        cy.get('[data-test=deal-profile-tabs] > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('.u-width-full > .u-relative > .react-dropdown > .loi_template_id__control > .loi_template_id__value-container').click()
        cy.contains('Global Template').click()
        cy.wait(3000)
        cy.contains('generation date') })
    it('Opening a proposal with a selected template', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2568234")
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.wait(3000)
        cy.contains('Six (6)') })
    it('Opening a proposal with no template selected & selecting one via Info tab', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2567961")
        cy.get('[data-test=deal-profile-tabs] > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('.gr-16 > .u-relative > .react-dropdown > .loi_template_id__control > .loi_template_id__value-container').click()        
        cy.contains('Global Template').click()
        cy.wait(3000)
        cy.contains('generation date') })
    it('Unsubstitute when data is deleted', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2568234")
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.wait(3000)
        cy.get('[aria-controls="term,0"]').click()
        cy.get('[data-test=remove_rent_escalation]').click()
        cy.contains('with rent escalation') })
    it('Substituting data & making sure the LOI preview updates', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2567961")
        cy.get('[data-test=deal-profile-tabs] > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.get('.u-width-full > .u-relative > .react-dropdown > .loi_template_id__control > .loi_template_id__value-container').click()
        cy.contains('Global Template').click()
        cy.wait(3000)
        cy.get('[aria-controls="term,0"]').click()
        cy.get('[data-test=add_first_rent_escalation] > .Icon-icon_3HmFe').click()
        cy.get(':nth-child(7) > :nth-child(1) > .u-flex > .gr-16 > .form-control-container > .form-control').type('10/10/2021')
        cy.get(':nth-child(7) > :nth-child(1) > .u-flex > .gr-8').click()
        cy.get(':nth-child(8) > :nth-child(1) > .u-flex > .gr-16 > .vts-input > .form-control-container > .form-control').type('72')
        cy.get('.u-p-vert-lg > :nth-child(1) > .u-flex-justify-between > .gr-16 > div.u-flex > .u-no-p-right > .vts-input > .form-control-container > .u-no-border-right').type('2.5')
        cy.get('.u-p-top-lg > :nth-child(1) > .u-flex-justify-between > .gr-16 > div.u-flex > .u-no-p-right > .vts-input > .form-control-container > .u-no-border-right').type('4.5')
        cy.contains('4.5%') })
    it('Unsubstitute option tag when data is deleted', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2568234")
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.wait(3000)
        cy.get('[aria-controls="options_and_more"]').click()
        cy.get('.RemoveIcon-removeIcon_2Doy7 > .Icon-icon_3HmFe').click()
        cy.contains('option use description') })
    it('Substitute option tag when data is added', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2568234")
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.wait(3000)
        cy.get('[aria-controls="options_and_more"]').click()
        cy.get('.RemoveIcon-removeIcon_2Doy7 > .Icon-icon_3HmFe').click()
        cy.contains('option use description') 
        cy.get('[data-test=select-option-or-right-type] > .Icon-icon_3HmFe').click()
        cy.get('.option_type__value-container').type('use')
        cy.get('[data-test=dropdownOption-Use]').click()
        cy.get('[data-test=add-option-or-right] > .button-text').click()
        cy.wait(3000)
        cy.contains('use super-beta description 3%') })
    it('All formatting pipes apply to preview', () => {
        cy.visit("https://acceptance.vts.com/lease/deals/2568236")
        cy.get('[data-test=add-proposal] > .button-text').click()
        cy.get('.u-p-lg-horz > .Tabs-tabs_28ejd > [data-test=tab-option]').click()
        cy.wait(5000)
        cy.contains('Thirty-five dollars ($35.00) per rentable square foot per month')
        cy.contains('THIRTY-FIVE DOLLARS ($35.00) PER RENTABLE SQUARE FOOT PER MONTH')
        cy.contains('Thirty-five dollars ($35.00) per rentable square foot per month')
        cy.contains('thirty-five dollars ($35.00) per rentable square foot per month')
        cy.contains('$35.00 /sf/mo')  

    })
})